# docker-images/Dockerfile.typescript

FROM node:18-slim
RUN apt-get update && apt-get install -y coreutils
WORKDIR /app

# install TypeScript compiler
RUN npm install -g esbuild@0.19.11

# set non-privileged user
RUN useradd -m runner
USER runner

ENV HOME=/app
